### ISSUE TITLE
add some features

### ISSUE THREAD

**Issue by andres11av** [BoranCanOzel/bf1-external#1]
I tried it and it works very well, but consider adding only esp enemy and only aimbot enemy, thank you very much, great job

**Comment by BoranCanOzel** [comment]
Hi andres11av,

Thank you so much for trying out the project and for your feedback! I'm glad to hear that it's working well for you. Your suggestions for adding ESP enemy and aimbot enemy features are interesting and could definitely enhance the functionality.

I'm open to expanding the project's features as more people show interest in it. The more engagement we get from users like you, the more motivation there is to develop new features. So, if the project gathers more interest, I'll certainly consider adding those capabilities.

Thanks again for your support, and feel free to spread the word to help the project grow!

Best regards,
Boran Can Ozel
